### ISSUE TITLE
Bluetooth does not reconnect in gadget Bridge 

### ISSUE THREAD

**Issue by joseph58tech** [JF002/InfiniTime#620] opened 2021-08-28 07:03 UTC
Some times when the watch disconnects from my phone (let's say it is out of range) it doesn't reconnect until I've restarted the watch, and on top of that I have to disconnect it from gadget Bridge when restarting the watch because if I don't the watch won't reconnect

**Comment by Avamander** [comment] 2021-08-28 08:11
Duplicate of https://github.com/JF002/InfiniTime/issues/302

**Closed** 2021-09-08 23:57 UTC
Labels: duplicate
