### ISSUE TITLE
Bluetooth disconnecting everyday

### ISSUE THREAD

**Issue by SteeveGL** [JF002/InfiniTime#686] opened 2021-09-23 12:40 UTC
Since I received my watch, every day the Bluetooth disconnect. I reset (restart) the watch then the connection come back.

v1.4.0
Using Gadgetbridge on Android.

**Comment by arvchristos** [comment] 2021-09-23 13:21
This happens to me too. I am using v1.4.0 and Gadgetbridge as the OP.

**Comment by LlamasJM** [comment] 2021-09-23 15:43
Me too. Using v1.4.0 and Gadgetbridge. Not necessary reset the watch. Only quit PineTime from Gadgetbridge, wait some minutes, and search and connect again.

**Comment by bhibb** [comment] 2021-09-23 15:56
This happens to me, too, but with the Infini-iOS app on iPhone. I wish there was a way to set the watch into a Bluetooth searching mode to have it start looking for devices on demand.

**Comment by imp667** [comment] 2021-09-24 02:16
Same issue here too. The update is really huge improvement but like others every day I have to remove the pinetime the readd and the. Disconnect then connect and things work.

**Comment by Paggios** [comment] 2021-09-24 10:06
yes, same problem. This issue appens also using wasp os?

**Comment by serjor** [comment] 2021-09-24 12:19
Hopefully, I'm not alone with this problem :disappointed:

**Comment by Avamander** [comment] 2021-09-24 12:23
Duplicate of https://github.com/JF002/InfiniTime/issues/302

@serjor If you just have the same issue, use reacts instead of comments.

**Comment by SteeveGL** [comment] 2021-09-24 12:24
> Duplicate of #302
> 
> @serjor If you just have the same issue, use reacts instead of comments.

It's not related

**Comment by Avamander** [comment] 2021-09-24 12:25
@SteeveGL it is the same issue.

**Comment by Avamander** [comment] 2021-09-24 12:27
The very least it's a duplicate of https://github.com/JF002/InfiniTime/issues/654, but that's again still the same underlying issue.

**Comment by SteeveGL** [comment] 2021-09-24 12:28
> @SteeveGL it is the same issue.

No, it has nothing todo with the airline mode. 

Before 7am works find. After 7am Bluetooth disconnect. Required reset.

**Comment by Avamander** [comment] 2021-09-24 12:30
@SteeveGL Try to ignore the title for a second, it hasn't been updated and it's user-chosen. In any case, use search before opening a new issue.

**Comment by SteeveGL** [comment] 2021-09-24 12:30
> @SteeveGL Try to ignore the title for a second, it hasn't been updated and it's user-chosen. In any case, use search before opening a new issue.

I did. Not duplicate

**Comment by joseph58tech** [comment] 2021-09-27 13:21
This problem is still ongoing in v1.5, just so you know

**Comment by Avamander** [comment] 2021-09-27 13:43
As the changelog doesn't say, the update doesn't contain any fixes to this issue.

**Comment by SteeveGL** [comment] 2021-09-27 14:08
I notice 2 distincts issues.

1. The watch disconnect by itself. Happening every day. Reset fix the issue. 
2. Gadgetbridge disconnect the watch. Happening randomly. Reset the watch doesn't fix the issue. Quitting Gadgetbridge doesn't fix the issue. Removing the watch from Gadgetbridge and adding it back fox the issue.

I'm talking about #1 here.

**Comment by SteeveGL** [comment] 2021-09-28 12:05
> @SteeveGL Does this issue always occur at the same time of day e.g. 7am? On how many consecutive days has this occured?

No it's not fix on a specific time. But must of the time it happens in the morning. It's close to be every 24h after the last reset.

> Issue #302 which will likely be fixed by #688 means that if the watch disconnects at any point after roughly 18.2 hours (e.g. moved out of range of the phone or phone drops the connection) then the watch no longer sends out bluetooth advertisement packets and has to be reset before being able to connect over bluetooth again.

Since I have my watch, I never been out of range very long.

**Comment by tmilburn** [comment] 2021-09-28 12:31
If you have the [nRF connect app](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en_GB&gl=US) then you can debug the bluetooth connection and work out the reason for the disconnection. This may be for many reasons not just out of range.

**Comment by SteeveGL** [comment] 2021-09-28 13:35
> If you have the [nRF connect app](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en_GB&gl=US) then you can debug the bluetooth connection and work out the reason for the disconnection. This may be for many reasons not just out of range.

```
nRF Connect, 2021-09-28
InfiniTime (F8:8A:34:AE:41:43)
V	09:01:07.440	Connecting to F8:8A:34:AE:41:43...
D	09:01:07.440	gatt = device.connectGatt(autoConnect = false, TRANSPORT_LE, preferred PHY = LE 1M)
D	09:01:07.474	[Callback] Connection state changed with status: 0 and new state: CONNECTED (2)
I	09:01:07.474	Connected to F8:8A:34:AE:41:43
D	09:01:07.474	wait(1600ms)
V	09:01:09.074	Discovering services...
D	09:01:09.074	gatt.discoverServices()
D	09:01:09.105	[Callback] Services discovered with status: 0
I	09:01:09.105	Services discovered
V	09:01:09.133	Generic Access (0x1800)
- Device Name [R] (0x2A00)
- Appearance [R] (0x2A01)
Generic Attribute (0x1801)
- Service Changed [I] (0x2A05)
   Client Characteristic Configuration (0x2902)
Device Information (0x180A)
- Manufacturer Name String [R] (0x2A29)
- Model Number String [R] (0x2A24)
- Serial Number String [R] (0x2A25)
- Firmware Revision String [R] (0x2A26)
- Hardware Revision String [R] (0x2A27)
- Software Revision String [R] (0x2A28)
Current Time Service (0x1805)
- Current Time [R W] (0x2A2B)
Unknown Service (00000000-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [N] (00000001-78fc-48fe-8e23-433b3a1942d0)
   Client Characteristic Configuration (0x2902)
- Unknown Characteristic [R W] (00000002-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (00000004-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (00000003-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (00000005-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (00000006-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (00000007-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (00000007-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (00000008-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (00000009-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (0000000a-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (0000000b-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (0000000c-78fc-48fe-8e23-433b3a1942d0)
Unknown Service (00010000-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (00010001-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (00010002-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (00010003-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (00010004-78fc-48fe-8e23-433b3a1942d0)
Alert Notification Service (0x1811)
- New Alert [W] (0x2A46)
- Unknown Characteristic [N] (00020001-78fc-48fe-8e23-433b3a1942d0)
   Client Characteristic Configuration (0x2902)
Device Firmware Update Service (00001530-1212-efde-1523-785feabcd123)
- DFU Packet [WNR] (00001532-1212-efde-1523-785feabcd123)
- DFU Control Point [N W] (00001531-1212-efde-1523-785feabcd123)
   Client Characteristic Configuration (0x2902)
- DFU Version [R] (00001534-1212-efde-1523-785feabcd123)
Battery Service (0x180F)
- Battery Level [N R] (0x2A19)
   Client Characteristic Configuration (0x2902)
Immediate Alert (0x1802)
- Alert Level [WNR] (0x2A06)
Heart Rate (0x180D)
- Heart Rate Measurement [N R] (0x2A37)
   Client Characteristic Configuration (0x2902)
D	09:01:09.133	gatt.setCharacteristicNotification(00002a05-0000-1000-8000-00805f9b34fb, true)
D	09:01:09.136	gatt.setCharacteristicNotification(00000001-78fc-48fe-8e23-433b3a1942d0, true)
D	09:01:09.137	gatt.setCharacteristicNotification(00020001-78fc-48fe-8e23-433b3a1942d0, true)
D	09:01:09.137	gatt.setCharacteristicNotification(00002a19-0000-1000-8000-00805f9b34fb, true)
D	09:01:09.138	gatt.setCharacteristicNotification(00002a37-0000-1000-8000-00805f9b34fb, true)
V	09:02:10.291	Reading all characteristics...
V	09:02:10.291	Reading characteristic 00002a00-0000-1000-8000-00805f9b34fb
D	09:02:10.291	gatt.readCharacteristic(00002a00-0000-1000-8000-00805f9b34fb)
I	09:02:10.373	Read Response received from 00002a00-0000-1000-8000-00805f9b34fb, value: (0x) 49-6E-66-69-6E-69-54-69-6D-65, "InfiniTime"
A	09:02:10.373	"InfiniTime" received
V	09:02:10.384	Reading characteristic 00002a01-0000-1000-8000-00805f9b34fb
D	09:02:10.384	gatt.readCharacteristic(00002a01-0000-1000-8000-00805f9b34fb)
I	09:02:10.463	Read Response received from 00002a01-0000-1000-8000-00805f9b34fb, value: (0x) 00-00
A	09:02:10.463	"[0] Unknown" received
V	09:02:10.475	Reading characteristic 00002a29-0000-1000-8000-00805f9b34fb
D	09:02:10.475	gatt.readCharacteristic(00002a29-0000-1000-8000-00805f9b34fb)
I	09:02:10.553	Read Response received from 00002a29-0000-1000-8000-00805f9b34fb, value: (0x) 50-49-4E-45-36-34, "PINE64"
A	09:02:10.553	"PINE64" received
V	09:02:10.563	Reading characteristic 00002a24-0000-1000-8000-00805f9b34fb
D	09:02:10.563	gatt.readCharacteristic(00002a24-0000-1000-8000-00805f9b34fb)
I	09:02:10.642	Read Response received from 00002a24-0000-1000-8000-00805f9b34fb, value: (0x) 50-69-6E-65-54-69-6D-65, "PineTime"
A	09:02:10.642	"PineTime" received
V	09:02:10.651	Reading characteristic 00002a25-0000-1000-8000-00805f9b34fb
D	09:02:10.651	gatt.readCharacteristic(00002a25-0000-1000-8000-00805f9b34fb)
I	09:02:10.732	Read Response received from 00002a25-0000-1000-8000-00805f9b34fb, value: (0x) 30, "0"
A	09:02:10.732	"0" received
V	09:02:10.740	Reading characteristic 00002a26-0000-1000-8000-00805f9b34fb
D	09:02:10.740	gatt.readCharacteristic(00002a26-0000-1000-8000-00805f9b34fb)
I	09:02:10.822	Read Response received from 00002a26-0000-1000-8000-00805f9b34fb, value: (0x) 31-2E-34-2E-30, "1.4.0"
A	09:02:10.822	"1.4.0" received
V	09:02:10.832	Reading characteristic 00002a27-0000-1000-8000-00805f9b34fb
D	09:02:10.832	gatt.readCharacteristic(00002a27-0000-1000-8000-00805f9b34fb)
I	09:02:10.913	Read Response received from 00002a27-0000-1000-8000-00805f9b34fb, value: (0x) 31-2E-30-2E-30, "1.0.0"
A	09:02:10.913	"1.0.0" received
V	09:02:10.922	Reading characteristic 00002a28-0000-1000-8000-00805f9b34fb
D	09:02:10.922	gatt.readCharacteristic(00002a28-0000-1000-8000-00805f9b34fb)
I	09:02:11.002	Read Response received from 00002a28-0000-1000-8000-00805f9b34fb, value: (0x) 49-6E-66-69-6E-69-54-69-6D-65, "InfiniTime"
A	09:02:11.002	"InfiniTime" received
V	09:02:11.031	Reading characteristic 00002a2b-0000-1000-8000-00805f9b34fb
D	09:02:11.031	gatt.readCharacteristic(00002a2b-0000-1000-8000-00805f9b34fb)
I	09:02:11.097	Read Response received from 00002a2b-0000-1000-8000-00805f9b34fb, value: (0x) E5-07-09-1C-09-02-06-00-00
A	09:02:11.097	"Invalid data syntax: (0x) E5-07-09-1C-09-02-06-00-00" received
V	09:02:11.104	Reading characteristic 00000002-78fc-48fe-8e23-433b3a1942d0
D	09:02:11.104	gatt.readCharacteristic(00000002-78fc-48fe-8e23-433b3a1942d0)
I	09:02:11.183	Read Response received from 00000002-78fc-48fe-8e23-433b3a1942d0, value: 0 bytes
V	09:02:11.194	Reading characteristic 00000004-78fc-48fe-8e23-433b3a1942d0
D	09:02:11.194	gatt.readCharacteristic(00000004-78fc-48fe-8e23-433b3a1942d0)
I	09:02:11.272	Read Response received from 00000004-78fc-48fe-8e23-433b3a1942d0, value: 0 bytes
V	09:02:11.286	Reading characteristic 00000003-78fc-48fe-8e23-433b3a1942d0
D	09:02:11.286	gatt.readCharacteristic(00000003-78fc-48fe-8e23-433b3a1942d0)
I	09:02:11.362	Read Response received from 00000003-78fc-48fe-8e23-433b3a1942d0, value: 0 bytes
V	09:02:11.371	Reading characteristic 00000005-78fc-48fe-8e23-433b3a1942d0
D	09:02:11.371	gatt.readCharacteristic(00000005-78fc-48fe-8e23-433b3a1942d0)
I	09:02:11.452	Read Response received from 00000005-78fc-48fe-8e23-433b3a1942d0, value: 0 bytes
V	09:02:11.461	Reading characteristic 00000006-78fc-48fe-8e23-433b3a1942d0
D	09:02:11.462	gatt.readCharacteristic(00000006-78fc-48fe-8e23-433b3a1942d0)
I	09:02:11.542	Read Response received from 00000006-78fc-48fe-8e23-433b3a1942d0, value: 0 bytes
V	09:02:11.553	Reading characteristic 00000007-78fc-48fe-8e23-433b3a1942d0
D	09:02:11.553	gatt.readCharacteristic(00000007-78fc-48fe-8e23-433b3a1942d0)
I	09:02:11.632	Read Response received from 00000007-78fc-48fe-8e23-433b3a1942d0, value: 0 bytes
V	09:02:11.643	Reading characteristic 00000007-78fc-48fe-8e23-433b3a1942d0
D	09:02:11.643	gatt.readCharacteristic(00000007-78fc-48fe-8e23-433b3a1942d0)
I	09:02:11.723	Read Response received from 00000007-78fc-48fe-8e23-433b3a1942d0, value: 0 bytes
V	09:02:11.734	Reading characteristic 00000008-78fc-48fe-8e23-433b3a1942d0
D	09:02:11.734	gatt.readCharacteristic(00000008-78fc-48fe-8e23-433b3a1942d0)
I	09:02:11.813	Read Response received from 00000008-78fc-48fe-8e23-433b3a1942d0, value: 0 bytes
V	09:02:11.830	Reading characteristic 00000009-78fc-48fe-8e23-433b3a1942d0
D	09:02:11.830	gatt.readCharacteristic(00000009-78fc-48fe-8e23-433b3a1942d0)
I	09:02:11.904	Read Response received from 00000009-78fc-48fe-8e23-433b3a1942d0, value: 0 bytes
V	09:02:11.919	Reading characteristic 0000000a-78fc-48fe-8e23-433b3a1942d0
D	09:02:11.919	gatt.readCharacteristic(0000000a-78fc-48fe-8e23-433b3a1942d0)
I	09:02:11.993	Read Response received from 0000000a-78fc-48fe-8e23-433b3a1942d0, value: 0 bytes
V	09:02:12.004	Reading characteristic 0000000b-78fc-48fe-8e23-433b3a1942d0
D	09:02:12.004	gatt.readCharacteristic(0000000b-78fc-48fe-8e23-433b3a1942d0)
I	09:02:12.082	Read Response received from 0000000b-78fc-48fe-8e23-433b3a1942d0, value: 0 bytes
V	09:02:12.094	Reading characteristic 0000000c-78fc-48fe-8e23-433b3a1942d0
D	09:02:12.094	gatt.readCharacteristic(0000000c-78fc-48fe-8e23-433b3a1942d0)
I	09:02:12.173	Read Response received from 0000000c-78fc-48fe-8e23-433b3a1942d0, value: 0 bytes
V	09:02:12.173	Reading characteristic 00010001-78fc-48fe-8e23-433b3a1942d0
D	09:02:12.173	gatt.readCharacteristic(00010001-78fc-48fe-8e23-433b3a1942d0)
I	09:02:12.262	Read Response received from 00010001-78fc-48fe-8e23-433b3a1942d0, value: 0 bytes
V	09:02:12.291	Reading characteristic 00010002-78fc-48fe-8e23-433b3a1942d0
D	09:02:12.291	gatt.readCharacteristic(00010002-78fc-48fe-8e23-433b3a1942d0)
I	09:02:12.352	Read Response received from 00010002-78fc-48fe-8e23-433b3a1942d0, value: 0 bytes
V	09:02:12.362	Reading characteristic 00010003-78fc-48fe-8e23-433b3a1942d0
D	09:02:12.362	gatt.readCharacteristic(00010003-78fc-48fe-8e23-433b3a1942d0)
I	09:02:12.442	Read Response received from 00010003-78fc-48fe-8e23-433b3a1942d0, value: 0 bytes
V	09:02:12.457	Reading characteristic 00010004-78fc-48fe-8e23-433b3a1942d0
D	09:02:12.457	gatt.readCharacteristic(00010004-78fc-48fe-8e23-433b3a1942d0)
I	09:02:12.533	Read Response received from 00010004-78fc-48fe-8e23-433b3a1942d0, value: 0 bytes
V	09:02:12.545	Reading characteristic 00001534-1212-efde-1523-785feabcd123
D	09:02:12.545	gatt.readCharacteristic(00001534-1212-efde-1523-785feabcd123)
I	09:02:12.624	Read Response received from 00001534-1212-efde-1523-785feabcd123, value: (0x) 4C-00
A	09:02:12.624	"Version: 0.76
Supported features:
- Firmware type and size included in the Init packet
- Signed init packet required
- SHA-256 firmware hash in the Extended DFU Init packet
- Service Changed characteristic supported
- Service Changed indication when bonded
- Different device address in non-buttonless DFU
- Extended DFU Init packet required
- SoftDevice OTA update
- Bootloader OTA update
- Application OTA update" received
V	09:02:12.640	Reading characteristic 00002a19-0000-1000-8000-00805f9b34fb
D	09:02:12.640	gatt.readCharacteristic(00002a19-0000-1000-8000-00805f9b34fb)
I	09:02:12.714	Read Response received from 00002a19-0000-1000-8000-00805f9b34fb, value: (0x) 45, "E"
A	09:02:12.714	"69%" received
V	09:02:12.725	Reading characteristic 00002a37-0000-1000-8000-00805f9b34fb
D	09:02:12.725	gatt.readCharacteristic(00002a37-0000-1000-8000-00805f9b34fb)
I	09:02:12.804	Read Response received from 00002a37-0000-1000-8000-00805f9b34fb, value: (0x) 00-00
A	09:02:12.804	"Heart Rate Measurement: 0 bpm,
Sensor Contact Not Supported" received
V	09:02:12.819	28 characteristics read
I	09:09:58.443	Notification received from 00002a19-0000-1000-8000-00805f9b34fb, value: (0x) 3A, ":"
A	09:09:58.443	"58%" received
I	09:19:44.454	Notification received from 00002a19-0000-1000-8000-00805f9b34fb, value: (0x) 39, "9"
A	09:19:44.455	"57%" received
D	09:23:43.559	[Callback] Connection state changed with status: 8 and new state: DISCONNECTED (0)
E	09:23:43.560	Error 8 (0x8): GATT CONN TIMEOUT
I	09:23:43.560	Disconnected
D	09:23:43.597	[Broadcast] Action received: android.bluetooth.device.action.ACL_DISCONNECTED
D	09:25:08.542	[Broadcast] Action received: android.bluetooth.device.action.ACL_CONNECTED
D	09:25:08.542	gatt.close()
D	09:25:08.573	wait(200)
V	09:25:08.773	Connecting to F8:8A:34:AE:41:43...
D	09:25:08.774	gatt = device.connectGatt(autoConnect = false, TRANSPORT_LE, preferred PHY = LE 1M)
D	09:25:08.798	[Callback] Connection state changed with status: 0 and new state: CONNECTED (2)
I	09:25:08.798	Connected to F8:8A:34:AE:41:43
D	09:25:08.798	wait(1600ms)
I	09:25:09.012	Connection parameters updated (interval: 7.5ms, latency: 0, timeout: 5000ms)
I	09:25:10.046	Connection parameters updated (interval: 45.0ms, latency: 0, timeout: 5000ms)
V	09:25:10.399	Discovering services...
D	09:25:10.399	gatt.discoverServices()
D	09:25:10.416	[Callback] Services discovered with status: 0
I	09:25:10.416	Services discovered
V	09:25:10.433	Generic Access (0x1800)
- Device Name [R] (0x2A00)
- Appearance [R] (0x2A01)
Generic Attribute (0x1801)
- Service Changed [I] (0x2A05)
   Client Characteristic Configuration (0x2902)
Device Information (0x180A)
- Manufacturer Name String [R] (0x2A29)
- Model Number String [R] (0x2A24)
- Serial Number String [R] (0x2A25)
- Firmware Revision String [R] (0x2A26)
- Hardware Revision String [R] (0x2A27)
- Software Revision String [R] (0x2A28)
Current Time Service (0x1805)
- Current Time [R W] (0x2A2B)
Unknown Service (00000000-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [N] (00000001-78fc-48fe-8e23-433b3a1942d0)
   Client Characteristic Configuration (0x2902)
- Unknown Characteristic [R W] (00000002-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (00000004-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (00000003-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (00000005-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (00000006-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (00000007-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (00000007-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (00000008-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (00000009-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (0000000a-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (0000000b-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (0000000c-78fc-48fe-8e23-433b3a1942d0)
Unknown Service (00010000-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (00010001-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (00010002-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (00010003-78fc-48fe-8e23-433b3a1942d0)
- Unknown Characteristic [R W] (00010004-78fc-48fe-8e23-433b3a1942d0)
Alert Notification Service (0x1811)
- New Alert [W] (0x2A46)
- Unknown Characteristic [N] (00020001-78fc-48fe-8e23-433b3a1942d0)
   Client Characteristic Configuration (0x2902)
Device Firmware Update Service (00001530-1212-efde-1523-785feabcd123)
- DFU Packet [WNR] (00001532-1212-efde-1523-785feabcd123)
- DFU Control Point [N W] (00001531-1212-efde-1523-785feabcd123)
   Client Characteristic Configuration (0x2902)
- DFU Version [R] (00001534-1212-efde-1523-785feabcd123)
Battery Service (0x180F)
- Battery Level [N R] (0x2A19)
   Client Characteristic Configuration (0x2902)
Immediate Alert (0x1802)
- Alert Level [WNR] (0x2A06)
Heart Rate (0x180D)
- Heart Rate Measurement [N R] (0x2A37)
   Client Characteristic Configuration (0x2902)
D	09:25:10.433	gatt.setCharacteristicNotification(00002a05-0000-1000-8000-00805f9b34fb, true)
D	09:25:10.435	gatt.setCharacteristicNotification(00000001-78fc-48fe-8e23-433b3a1942d0, true)
D	09:25:10.436	gatt.setCharacteristicNotification(00020001-78fc-48fe-8e23-433b3a1942d0, true)
D	09:25:10.437	gatt.setCharacteristicNotification(00002a19-0000-1000-8000-00805f9b34fb, true)
D	09:25:10.437	gatt.setCharacteristicNotification(00002a37-0000-1000-8000-00805f9b34fb, true)

```

Disconnected then I did a reset.
> D	09:23:43.559	[Callback] Connection state changed with status: 8 and new state: DISCONNECTED (0)
E	09:23:43.560	Error 8 (0x8): GATT CONN TIMEOUT
I	09:23:43.560	Disconnected
D	09:23:43.597	[Broadcast] Action received: android.bluetooth.device.action.ACL_DISCONNECTED
D	09:25:08.542	[Broadcast] Action received: android.bluetooth.device.action.ACL_CONNECTED
D	09:25:08.542	gatt.close()

Close to be exactly 24h since my last reset. I will let the debug running to see tomorrow to have the exact timestamp.

**Comment by JF002** [comment] 2021-09-30 19:17
InfiniTime 1.5 and 1.6 brought many improvements the BLE connectivity. While I doubt those changes fix **all** connectivity issues, they certainly fix most of them. I think this one (BLE that disconnects after a day) is one of them. I'll close this issue, but feel free to open a new one if you encounter another BLE issue on InfiniTime 1.6 (and if it doesn't exist yet).

**Closed by JF002** 2021-09-30 19:17 UTC
